# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/trunglx/Downloads/github/color_correction

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/trunglx/Downloads/github/color_correction

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trunglx/Downloads/github/color_correction/CMakeFiles /home/trunglx/Downloads/github/color_correction/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trunglx/Downloads/github/color_correction/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CCM

# Build rule for target.
CCM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CCM
.PHONY : CCM

# fast build rule for target.
CCM/fast:
	$(MAKE) -f CMakeFiles/CCM.dir/build.make CMakeFiles/CCM.dir/build
.PHONY : CCM/fast

src/applyhsl2video.o: src/applyhsl2video.cpp.o

.PHONY : src/applyhsl2video.o

# target to build an object file
src/applyhsl2video.cpp.o:
	$(MAKE) -f CMakeFiles/CCM.dir/build.make CMakeFiles/CCM.dir/src/applyhsl2video.cpp.o
.PHONY : src/applyhsl2video.cpp.o

src/applyhsl2video.i: src/applyhsl2video.cpp.i

.PHONY : src/applyhsl2video.i

# target to preprocess a source file
src/applyhsl2video.cpp.i:
	$(MAKE) -f CMakeFiles/CCM.dir/build.make CMakeFiles/CCM.dir/src/applyhsl2video.cpp.i
.PHONY : src/applyhsl2video.cpp.i

src/applyhsl2video.s: src/applyhsl2video.cpp.s

.PHONY : src/applyhsl2video.s

# target to generate assembly for a file
src/applyhsl2video.cpp.s:
	$(MAKE) -f CMakeFiles/CCM.dir/build.make CMakeFiles/CCM.dir/src/applyhsl2video.cpp.s
.PHONY : src/applyhsl2video.cpp.s

src/mylib/hsl.o: src/mylib/hsl.cpp.o

.PHONY : src/mylib/hsl.o

# target to build an object file
src/mylib/hsl.cpp.o:
	$(MAKE) -f CMakeFiles/CCM.dir/build.make CMakeFiles/CCM.dir/src/mylib/hsl.cpp.o
.PHONY : src/mylib/hsl.cpp.o

src/mylib/hsl.i: src/mylib/hsl.cpp.i

.PHONY : src/mylib/hsl.i

# target to preprocess a source file
src/mylib/hsl.cpp.i:
	$(MAKE) -f CMakeFiles/CCM.dir/build.make CMakeFiles/CCM.dir/src/mylib/hsl.cpp.i
.PHONY : src/mylib/hsl.cpp.i

src/mylib/hsl.s: src/mylib/hsl.cpp.s

.PHONY : src/mylib/hsl.s

# target to generate assembly for a file
src/mylib/hsl.cpp.s:
	$(MAKE) -f CMakeFiles/CCM.dir/build.make CMakeFiles/CCM.dir/src/mylib/hsl.cpp.s
.PHONY : src/mylib/hsl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CCM"
	@echo "... src/applyhsl2video.o"
	@echo "... src/applyhsl2video.i"
	@echo "... src/applyhsl2video.s"
	@echo "... src/mylib/hsl.o"
	@echo "... src/mylib/hsl.i"
	@echo "... src/mylib/hsl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

